# Generated by Django 5.2 on 2025-04-28 18:23

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextofkin",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a71df9c5-e0d0-4d99-9483-28c8f3d2ed84"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                default="Unknown", max_length=50, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(
                default="MX", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a71df9c5-e0d0-4d99-9483-28c8f3d2ed84"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
