# Generated by Django 5.2 on 2025-04-29 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_alter_nextofkin_id_alter_profile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextofkin",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("67f08adc-4382-4f09-980f-b7654fa7c291"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("67f08adc-4382-4f09-980f-b7654fa7c291"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
