# Generated by Django 5.2 on 2025-04-30 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_nextofkin_id_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextofkin",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b599ec75-fd63-44fd-bae8-d84450080088"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="employer_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Employer Name"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b599ec75-fd63-44fd-bae8-d84450080088"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
