# Generated by Django 5.2 on 2025-04-30 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_profile",
            "0004_alter_nextofkin_id_alter_profile_employer_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="nextofkin",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e3e665d7-816d-451f-8451-a35207caa757"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e3e665d7-816d-451f-8451-a35207caa757"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
