# Generated by Django 5.2 on 2025-05-03 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0006_alter_nextofkin_id_alter_profile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_currency",
            field=models.CharField(
                blank=True,
                choices=[("mexican_peso", "Mexican Peso"), ("us_dollar", "US Dollar")],
                max_length=20,
                null=True,
                verbose_name="Account Currency",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="account_type",
            field=models.CharField(
                blank=True,
                choices=[("current", "Current"), ("savings", "Savings")],
                max_length=20,
                null=True,
                verbose_name="Account Type",
            ),
        ),
        migrations.AlterField(
            model_name="nextofkin",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("03f7541c-b114-44b3-9dd9-93542bf75ba4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("03f7541c-b114-44b3-9dd9-93542bf75ba4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
