# Generated by Django 5.2 on 2025-04-28 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a71df9c5-e0d0-4d99-9483-28c8f3d2ed84"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
