# Generated by Django 5.2 on 2025-04-30 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_contentview_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b599ec75-fd63-44fd-bae8-d84450080088"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
