# Generated by Django 5.2 on 2025-04-30 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_contentview_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e3e665d7-816d-451f-8451-a35207caa757"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
