# Generated by Django 5.2 on 2025-05-02 00:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_contentview_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f25407c2-e710-4f46-be20-8515770a955f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
