# Generated by Django 5.2 on 2025-05-03 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_contentview_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("03f7541c-b114-44b3-9dd9-93542bf75ba4"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
