# Generated by Django 5.2 on 2025-04-28 18:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("072a6398-8b0e-4601-936c-89e4979e208c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
