# Generated by Django 5.2 on 2025-04-29 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fb990bf6-8f6a-44fb-973d-2ce2528b5c05"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
