# Generated by Django 5.2 on 2025-04-30 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d4c5a19b-675f-4171-99eb-3bd0e4e4a350"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
