# Generated by Django 5.2 on 2025-04-30 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5f6aa103-9f7f-4014-afde-d502038d2a1c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
