# Generated by Django 5.2 on 2025-05-02 00:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7a96e5c6-77cf-4985-ac6f-84b280b41c60"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
