# Generated by Django 5.2 on 2025-05-03 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0007_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b62e4dc8-a124-4bb9-85dc-63bb0a02c651"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
